f = open("/Users/macbook/Desktop/python_learning/fileIO/file1.txt","r")
data = f.read()
print(data)
print(type(data))
f.close()
line1 = f.readline()
print(line1)
line2 = f.readline()
print(line2)
f.close()